version: "3.5"

networks:
    final_project:
        driver: bridge

services:
    redis:
        image: redis
        networks:
            - final_project
    flask:
        image: zoeclairewatson/practicingapp-api:1.0
        command: "/app/api.py"
        ports:
            - "5000:5000"
        environment:
            REDIS_IP: "redis"
        networks:
            - final_project
    worker:
        image: zoeclairewatson/practicingapp-worker:1.0
        command: "/app/worker.py"
        environment:
            REDIS_IP: "redis"
        networks:
            - final_project
